/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javalab3;
import data.User;
import java.awt.Image;
import javax.swing.ImageIcon;

public class viewDetailsPanel extends javax.swing.JPanel {
    User finalUser = new User();

    /**
     * Creates new form viewDetailsPanel
     * @param inputUser
     */
    public viewDetailsPanel(User inputUser) {
        this.finalUser = inputUser;
        initComponents();
        setAllDetailFields(finalUser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        majorLabel = new javax.swing.JLabel();
        photoDisplayLabel = new javax.swing.JLabel();
        fnameLabel = new javax.swing.JLabel();
        lnameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        phnumberLabel = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        fnameDetailLabel = new javax.swing.JLabel();
        lnameDetailLabel = new javax.swing.JLabel();
        ageDetailLabel = new javax.swing.JLabel();
        phoneDetailLabel = new javax.swing.JLabel();
        emailDetailLabel = new javax.swing.JLabel();
        addressDetailLabel = new javax.swing.JLabel();
        cityDetailLabel = new javax.swing.JLabel();
        majorDetailLabel = new javax.swing.JLabel();
        countryDetailLabel = new javax.swing.JLabel();

        emailLabel.setText("Email:");

        cityLabel.setText("City:");

        addressLabel.setText("Address:");

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleLabel.setText("Your Details:");

        majorLabel.setText("Major:");

        fnameLabel.setText("First Name:");

        lnameLabel.setText("Last Name:");

        ageLabel.setText("Age");

        phnumberLabel.setText("Phone Number:");

        countryLabel.setText("Country:");

        fnameDetailLabel.setText("fname");

        lnameDetailLabel.setText("lname");

        ageDetailLabel.setText("age");

        phoneDetailLabel.setText("phone");

        emailDetailLabel.setText("email");

        addressDetailLabel.setText("address");

        cityDetailLabel.setText("city");

        majorDetailLabel.setText("major");

        countryDetailLabel.setText("country");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(photoDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(majorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(countryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phnumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fnameDetailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lnameDetailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageDetailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneDetailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailDetailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressDetailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityDetailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(majorDetailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(countryDetailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(331, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(photoDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnameLabel)
                    .addComponent(fnameDetailLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnameLabel)
                    .addComponent(lnameDetailLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageDetailLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phnumberLabel)
                    .addComponent(phoneDetailLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailDetailLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressDetailLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(cityDetailLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryLabel)
                    .addComponent(countryDetailLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(majorLabel)
                    .addComponent(majorDetailLabel))
                .addGap(123, 123, 123))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressDetailLabel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel ageDetailLabel;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel cityDetailLabel;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel countryDetailLabel;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JLabel emailDetailLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel fnameDetailLabel;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JLabel lnameDetailLabel;
    private javax.swing.JLabel lnameLabel;
    private javax.swing.JLabel majorDetailLabel;
    private javax.swing.JLabel majorLabel;
    private javax.swing.JLabel phnumberLabel;
    private javax.swing.JLabel phoneDetailLabel;
    private javax.swing.JLabel photoDisplayLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

     void setAllDetailFields(User finalUser) {
        //PHOTO ADD
        ImageIcon imagePreview = new ImageIcon(finalUser.getPhoto());
        Image image = imagePreview.getImage().getScaledInstance(188, 159, Image.SCALE_SMOOTH);
        photoDisplayLabel.setIcon(new ImageIcon(image));
            
        fnameDetailLabel.setText(finalUser.getFirstName());
        lnameDetailLabel.setText(finalUser.getLastName());
        ageDetailLabel.setText(finalUser.getAge());
        phoneDetailLabel.setText(finalUser.getPhoneNumber());
        emailDetailLabel.setText(finalUser.getEmail());
        addressDetailLabel.setText(finalUser.getAddress());
        cityDetailLabel.setText(finalUser.getCity());
        countryDetailLabel.setText(finalUser.getCountry());
        majorDetailLabel.setText(finalUser.getMajor());
    }

}
